export const EMPLOYEE_MANAGEMENT_AUDIT_MODULE = 'EMPLOYEE_MANAGEMENT';
export const EMPLOYEE_MANAGEMENT_ENTITY_TYPE = 'Employee';

export const EmployeeManagementAuditAction = {
  CREATED: 'EMPLOYEE_CREATED',
  UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYMENT_CHANGED: 'EMPLOYEE_EMPLOYMENT_CHANGED',
  COMPENSATION_CHANGED: 'EMPLOYEE_COMPENSATION_CHANGED',
  RECURRING_PAYROLL_ITEM_CREATED: 'EMPLOYEE_RECURRING_PAYROLL_ITEM_CREATED',
  STATUS_CHANGED: 'EMPLOYEE_STATUS_CHANGED',
  PAYROLL_PROFILE_UPDATED: 'EMPLOYEE_PAYROLL_PROFILE_UPDATED',
  LEAVE_BALANCE_ADJUSTED: 'EMPLOYEE_LEAVE_BALANCE_ADJUSTED',
} as const;
