export const USER_MANAGEMENT_AUDIT_MODULE = 'USER_MANAGEMENT';

export const USER_MANAGEMENT_ENTITY_TYPE = 'User';

export const UserManagementAuditAction = {
  ROLES_REPLACED: 'USER_ROLES_REPLACED',

  COMPANY_ACCESS_REPLACED: 'USER_COMPANY_ACCESS_REPLACED',

  STATUS_CHANGED: 'USER_STATUS_CHANGED',
} as const;
